### ISSUE TITLE
java.lang.AbstractMethodError: abstract method not implemented

### ISSUE THREAD

**Issue by snowberry001** [GDG-Korea/PinterestLikeAdapterView#50]
i got this problem，anyone can help me? thx!

`Fatal Exception: java.lang.AbstractMethodError: abstract method not implemented
       at android.widget.AbsListView.fillGap(AbsListView.java)
       at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5136)
       at android.widget.AbsListView.onGenericMotionEvent(AbsListView.java:3804)
       at android.view.View.dispatchGenericMotionEventInternal(View.java:7801)
       at android.view.View.dispatchGenericMotionEvent(View.java:7782)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1824)
       at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1777)
       at android.view.View.dispatchGenericMotionEvent(View.java:7775)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2076)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1525)
       at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2494)
       at android.support.v7.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:73)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2030)
       at android.view.View.dispatchPointerEvent(View.java:7888)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3978)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3857)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3423)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3473)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3442)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3549)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3450)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3606)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3423)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3473)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3442)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3450)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3423)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5626)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5606)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5577)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5706)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:5045)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by Mees0x4E** [comment]
It might help if you send some code...
